# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pencere.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 121, 31))
        self.label_2.setObjectName("label_2")
        self.kultxt = QtWidgets.QLineEdit(self.centralwidget)
        self.kultxt.setGeometry(QtCore.QRect(130, 30, 113, 20))
        self.kultxt.setObjectName("kultxt")
        self.sifretxt = QtWidgets.QLineEdit(self.centralwidget)
        self.sifretxt.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.sifretxt.setObjectName("sifretxt")
        self.eklebtn = QtWidgets.QPushButton(self.centralwidget)
        self.eklebtn.setGeometry(QtCore.QRect(50, 150, 91, 23))
        self.eklebtn.setObjectName("eklebtn")
        self.duzeltbtn = QtWidgets.QPushButton(self.centralwidget)
        self.duzeltbtn.setGeometry(QtCore.QRect(160, 150, 75, 23))
        self.duzeltbtn.setObjectName("duzeltbtn")
        self.silmebtn = QtWidgets.QPushButton(self.centralwidget)
        self.silmebtn.setGeometry(QtCore.QRect(250, 150, 75, 23))
        self.silmebtn.setObjectName("silmebtn")
        self.aramabtn = QtWidgets.QPushButton(self.centralwidget)
        self.aramabtn.setGeometry(QtCore.QRect(330, 150, 75, 23))
        self.aramabtn.setObjectName("aramabtn")
        self.tablom = QtWidgets.QTableWidget(self.centralwidget)
        self.tablom.setGeometry(QtCore.QRect(30, 210, 651, 271))
        self.tablom.setRowCount(20)
        self.tablom.setColumnCount(3)
        self.tablom.setObjectName("tablom")
        self.yetkicmb = QtWidgets.QComboBox(self.centralwidget)
        self.yetkicmb.setGeometry(QtCore.QRect(130, 110, 141, 22))
        self.yetkicmb.setObjectName("yetkicmb")
        self.yetkicmb.addItem("")
        self.yetkicmb.addItem("")
        self.yetkicmb.addItem("")
        self.listelebtn = QtWidgets.QPushButton(self.centralwidget)
        self.listelebtn.setGeometry(QtCore.QRect(420, 150, 75, 23))
        self.listelebtn.setObjectName("listelebtn")
        self.aramapanel = QtWidgets.QGroupBox(self.centralwidget)
        self.aramapanel.setGeometry(QtCore.QRect(530, 20, 251, 151))
        self.aramapanel.setObjectName("aramapanel")
        self.arayapbtn = QtWidgets.QPushButton(self.aramapanel)
        self.arayapbtn.setGeometry(QtCore.QRect(50, 80, 121, 31))
        self.arayapbtn.setObjectName("arayapbtn")
        self.arayicitxt = QtWidgets.QLineEdit(self.aramapanel)
        self.arayicitxt.setGeometry(QtCore.QRect(20, 30, 211, 20))
        self.arayicitxt.setObjectName("arayicitxt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Kullanıcı Adı "))
        self.label_2.setText(_translate("MainWindow", "Şifre"))
        self.eklebtn.setText(_translate("MainWindow", "Ekleme"))
        self.duzeltbtn.setText(_translate("MainWindow", "Düzeltme"))
        self.silmebtn.setText(_translate("MainWindow", "Silme"))
        self.aramabtn.setText(_translate("MainWindow", "Arama"))
        self.yetkicmb.setItemText(0, _translate("MainWindow", "Admin"))
        self.yetkicmb.setItemText(1, _translate("MainWindow", "Kullanıcı"))
        self.yetkicmb.setItemText(2, _translate("MainWindow", "Editör"))
        self.listelebtn.setText(_translate("MainWindow", "Lİsteleme"))
        self.aramapanel.setTitle(_translate("MainWindow", "Arama Yap"))
        self.arayapbtn.setText(_translate("MainWindow", "Arama Yap"))
